baseURL: "/"
languageCode: "zh-cn"
title: "断桥bian的博客"
theme: "PaperMod"


paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true


taxonomies:
    category: categories
    tag: tags
    series: series


params:
    defaultTheme: dark
    disableThemeToggle: true
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowToc: true
    profileMode:
        enabled: true
        title: "断桥bian" # optional default will be site title
        subtitle: "世界上本没有路，只是走的人多了而已。"
        imageUrl: "/image/wali_sky.jpeg" # optional
        imageTitle: "瓦利-仰望" # optional
        imageWidth: 200 # custom size
        imageHeight: 200 # custom size
        buttons:
            - name: "Github"
              url: "https://github.com/duanqiaobb"
            - name: "博客" 
              url: "/blog"
            - name: "关于" 
              url: "/resume"
