baseURL: "/"
languageCode: "zh-cn"
title: "断桥bian的博客"
theme: "PaperMod"


paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true


params:
    defaultTheme: auto
    disableThemeToggle: true
    profileMode:
        enabled: true
        title: "断桥bian" # optional default will be site title
        subtitle: "世界上本没有路，只是走的人多了而已。"
        imageUrl: "/image/wali_profile.jpeg" # optional
        imageTitle: "瓦利-仰望" # optional
        #imageWidth: 120 # custom size
        #imageHeight: 120 # custom size
        buttons:
            - name: "博客" 
              url: "/content/blog"
            - name: Github
              url: "https://github.com/duanqiaobb"

    socialIcons: # optional
        - name: "Github"
          url: "<link>"